ED1L3/ED1L3/Controllers/PartidonoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.IO;
using directorios = System.IO;
using TDA;
using ED1L3.Models;
using ED1L3.DBContest;
using System.Net;
using ED1L3.Controllers;

namespace ED1L3.Models
{
    public class PartidonoController : Controller
    {
        DefaultConnection<Partido, int> db = DefaultConnection<Partido, int>.getInstance;

    
        public ActionResult CargaArchivo(HttpPostedFileBase archivo)
        {
            db.AB.Nuevolog.convsersor = conversorno;
            List<Nodo<Partido, int>> nodos_a_insertar = new List<Nodo<Partido, int>>();
            Nodo<Partido, int> nuevo;

            db.datos.Clear();
            Carga_de_Archivo<Partido, int> archivo_json = new Carga_de_Archivo<Partido, int>();
            nodos_a_insertar = archivo_json.Cargajsoninterna(archivo, Server);
            for (int i = 0; i < nodos_a_insertar.Count; i++)
            {
                nuevo = nodos_a_insertar[i];
                nuevo.llave = nuevo.valor.Nopartido;

                db.datos.Clear();
                db.AB.Insertar(nuevo);
                db.AB.EnOrden(asignar_comparacion);
                db.AB.EnOrden(pasar_a_lista);
            }

            return RedirectToAction("Index");
        }



        // GET: Partidono
        public ActionResult Index()
        {
            return View(db.datos.ToList());
        }

        // GET: Partidono/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Partidono/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Partidono/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "Nopartido,FechaPartido,Grupo,Pais1,Pais2,Estadio ")]Partido partido)
        {
            db.AB.Nuevolog.convsersor = conversorno;

            try
            {
              
                
               
                // TODO: Add insert logic here
                Nodo<Partido, int> nueva_pais = new Nodo<Partido, int>(partido, null);
                nueva_pais.valor = partido;
                nueva_pais.llave = partido.Nopartido;
                db.datos.Clear();
                db.AB.Insertar(nueva_pais);
                db.AB.EnOrden(asignar_comparacion);
                db.AB.EnOrden(pasar_a_lista);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public void pasar_a_lista(Nodo<Partido, int> actual)
        {
            db.datos.Add(actual.valor);
        }

        public int comparador_no(int actual, int nuevo)
        {
            return actual.CompareTo(nuevo);

        }

        public void asignar_comparacion(Nodo<Partido, int> actual)
        {
            actual.comparador = comparador_no;
        }

        // GET: Partidono/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Partidono/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public string conversorno(int key)
        {

            return key.ToString();
        }

        public void Generar_Bitacora()
        {

            db.AB.Nuevolog.close();
        }
        public ActionResult Search()
        {
            return View();
        }
        [HttpPost]
        public void Search(int target)
        {
            bool seleccion = false;
            Nodo<Partido, int> node = db.AB.Raiz;
            if (node != null)
            {
                while (node != null)
                {
                    if (comparador_no(node.valor.Nopartido, target) > 0)
                    {
                        node = node.izquierdo;
                    }
                    else if (comparador_no(node.valor.Nopartido, target) < 0)
                    {
                        node = node.derecho;
                    }
                    else if (comparador_no(node.valor.Nopartido, target) == 0)
                    {
                        break;
                    }
                    else
                    {
                        seleccion = true;
                    }
                }
                List<string> lista = new List<string>();
                lista.Add(node.valor.Nopartido.ToString());
                lista.Add(node.valor.FechaPartido.ToString());
                lista.Add(node.valor.Grupo);
                lista.Add(node.valor.Pais1);
                lista.Add(node.valor.Pais2);
                lista.Add(node.valor.Estadio);
                if (seleccion == false)
                {
                    Response.Write("Equipo encontrado: " + " " + "No. Partido: " + " " + lista[0].ToString() + " " + "Fecha de partido: " + " " + lista[1].ToString() + " " + "Grupo: " + " " + lista[2].ToString() + " " + "Pais_1" + " " + lista[3].ToString() + " " + "Pais_2" + " " + lista[4].ToString() + " " + "Estadio: " + " " + lista[5].ToString());
                }
                else
                {
                    Response.Write("Equipo no encontrado");
                }
            }
        }
        // GET: Partidono/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Partido partido_buscado = db.datos.Find(x => x.Nopartido == id);

            if (partido_buscado == null)
            {

                return HttpNotFound();
            }
            return View(partido_buscado);
        }

        // POST: Partido/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                db.AB.Eliminar(db.datos.First(x => x.Nopartido == id).Nopartido);
                db.datos.Clear();
                db.AB.EnOrden(asignar_comparacion);
                db.AB.EnOrden(pasar_a_lista);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ED1L3/ED1L3/Views/Partidono/Create.cshtml
@model ED1L3.Models.Partido

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Partido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nopartido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nopartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nopartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaPartido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaPartido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaPartido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Grupo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Grupo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Grupo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pais1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pais1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pais1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pais2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pais2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pais2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estadio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Estadio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Estadio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ED1L3/ED1L3/Views/Partidono/Delete.cshtml
@model ED1L3.Models.Partido

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Partido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nopartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nopartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaPartido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Grupo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Grupo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pais2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pais2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estadio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estadio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ED1L3/ED1L3/Views/Partidono/Index.cshtml
@model IEnumerable<ED1L3.Models.Partido>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @Html.ActionLink("Buscar partidos por su numero", "Search")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nopartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaPartido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grupo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais1)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pais2)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estadio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nopartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaPartido)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Grupo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais1)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Pais2)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estadio)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Nopartido }) |
            @Html.ActionLink("Details", "Details", new { id = item.Nopartido }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Nopartido })
        </td>
    </tr>
}

</table>

<h3>Cargar Json</h3>
@using (Html.BeginForm("CargaArchivo", "Partidono", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <input type="file" name="archivo" />
        <input type="submit" value="Importar" />
    </div>
}

@using (Html.BeginForm("Generar_Bitacora", "Partidono", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">

        <input type="submit" value="Generar" />
    </div>
}

ED1L3/ED1L3/Views/Partidono/Search.cshtml
@{
    ViewBag.Title = "Search";
}

<h2>Search</h2>
<p>

</p>

<p>

</p>
@using (Html.BeginForm())
{
    <div class="form-group">
        <input type="text" name="target">
        <input type="submit" name="buscar">
    </div>


}